# Generated by Django 5.2.8 on 2025-11-21 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0008_remove_user_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('default', 'DEFAULT'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='default')),
                ('priority', models.CharField(choices=[('low', 'LOW'), ('default', 'DEFAULT'), ('high', 'HIGH'), ('highest', 'HIGHEST')], default='default')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_tasks', to='user.user')),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executive_tasks', to='user.user')),
            ],
        ),
    ]
