# Generated by Django 5.2.8 on 2025-11-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='expired_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('canceled', 'Canceled'), ('default', 'Default'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='default'),
        ),
    ]
