# Generated by Django 5.2.8 on 2025-11-21 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_created_at_alter_task_expired_at_and_more'),
        ('user', '0010_alter_role_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executive_tasks', to='user.user'),
        ),
        migrations.AlterField(
            model_name='task',
            name='expired_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
