# Generated by Django 5.2.8 on 2025-11-20 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userrefreshtoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrefreshtoken',
            old_name='user_id',
            new_name='user',
        ),
    ]
