# Generated by Django 5.2.8 on 2025-11-21 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_role_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='permissions',
        ),
    ]
