# Generated by Django 5.2.8 on 2025-11-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_role_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='level',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
